```yaml
# ALN Ecosystem Docker Image Build Workflow
# Version: 12.0.0
# Production-Grade Deployment

name: ALN Docker Image Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: src/Main/Docker
          push: true
          tags: |
            ghcr.io/Doctor0Evil/aln-ecosystem:${{ github.sha }}
            ghcr.io/Doctor0Evil/aln-ecosystem:latest
          build-args: |
            ALN_VERSION=${{ github.sha }}
            ALN_ENVIRONMENT=production

      - name: Create release
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          tag_name: v${{ github.sha }}
          release_name: ALN Ecosystem Release
          body: "ALN Ecosystem Docker image built and pushed to GHCR."
          generate_release_notes: true
```
