name: "ALN Corrections CI Master"
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
jobs:
  correct-aln-files:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-latest, macos-latest]
    concurrency:
      group: aln-corrections-${{ github.workflow }}-${{ github.ref_name }}
      cancel-in-progress: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Verify permissions and remote
        shell: bash
        run: |
          set -e
          git remote -v || { echo "No remote found"; exit 1; }
          git config --show-origin --get-all credential.helper || echo "No credential.helper configured"
          git ls-remote --exit-code origin &>/dev/null
      - name: Install PowerShell (non-Windows)
        if: runner.os != 'Windows'
        uses: PSModule/install-powershell@v1
        with:
          Version: 'latest'
      - name: Show PowerShell version
        shell: pwsh
        run: |
          Write-Host "PowerShell version:"
          $PSVersionTable
      - name: Run ALN corrections orchestrator
        shell: pwsh -NoProfile -ExecutionPolicy Bypass {0}
        run: |
          $ErrorActionPreference = 'Stop'
          $script = Join-Path $PWD 'scripts/correct-aln-files.ps1'
          if (-not (Test-Path $script)) { throw "Missing orchestrator script"; }
          & $script
      - name: Commit and safe push corrections
        shell: bash
        run: |
          set -e
          git config user.name "ALN Sync Bot"
          git config user.email "actions@github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "ALN corrections (auto orchestrated)"
          git pull --rebase origin "${GITHUB_REF_NAME}" || exit 1
          git push origin "${GITHUB_REF_NAME}" || exit 1
      - name: Upload logs artifacts
        uses: actions/upload-artifact@v4
        with:
          name: aln-corrections-logs
          path: |
            scripts/correction-*.log
            scripts/aln-debug-*.txt
          retention-days: 14
