# workflows/correct-aln-files.yml
name: "ALN Master Orchestrator - Github.Workflow.Corrections"
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
jobs:
  correct-aln-files:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-24.04, macos-latest]
    concurrency:
      group: aln-corrections-${{ github.workflow }}-${{ github.ref_name }}
      cancel-in-progress: false
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Verify permissions & git remote
        shell: bash
        run: |
          git remote -v || { echo "No remote found"; exit 1; }
          git config --show-origin --get-all credential.helper || echo "No credential.helper configured"
          if git ls-remote --exit-code origin &>/dev/null; then
            echo "✔ Remote OK"
          else
            echo "✖ Cannot reach remote 'origin'"
            exit 1
          fi
      - name: Install PowerShell (non-Windows)
        if: runner.os != 'Windows'
        uses: PSModule/install-powershell@v1
        with:
          Version: 'latest'
      - name: Show PowerShell version
        shell: pwsh
        run: |
          Write-Host "Running PowerShell:"
          $PSVersionTable
      - name: Run ALN corrections orchestrator (PowerShell)
        shell: pwsh -NoProfile -ExecutionPolicy Bypass {0}
        run: |
          $ErrorActionPreference = 'Stop'
          $orchestrator = Join-Path $PWD 'scripts/correct-aln-files.ps1'
          if (-not (Test-Path $orchestrator)) {
            throw "Missing orchestrator: $orchestrator"
          }
          & $orchestrator
      - name: Commit & safe push corrections
        shell: bash
        run: |
          git config user.name "ALN Sync Bot"
          git config user.email "actions@github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "ALN corrections (auto orchestrated)"
          attempt_push() {
            git pull --rebase origin "${GITHUB_REF_NAME}" || return 1
            git push origin "${GITHUB_REF_NAME}" || return 1
            echo "Push succeeded"
          }
          for i in 1 2 3; do
            if attempt_push; then exit 0; fi
            echo "Push failed (attempt $i). Retrying in $((i*5))s..."
            sleep $((i*5))
          done
          echo "Push failed after 3 attempts."
          exit 1
      - name: Upload logs artifacts
        uses: actions/upload-artifact@v4
        with:
          name: aln-corrections-logs
          path: |
            scripts/correction-*.log
            scripts/aln-debug-*.txt
          retention-days: 14
