name: ALN File Correction & Live Repo Sync

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  correct-and-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Normalize Line Endings
        run: |
          find . -type f ! -path "./.git/*" -exec dos2unix {} \;

      - name: Remove Trailing Whitespace
        run: |
          find . -type f ! -path "./.git/*" -exec sed -i "s/[ \t]*$//" {} \;

      - name: Format ALN files (if '.aln' extension)
        run: |
          for file in $(find . -type f -name "*.aln"); do
            # Placeholder for real ALN formatter, could be extended as linter is built
            sed -i "s/\r//g" "$file"
          done

      - name: Auto-commit & Push all changes
        run: |
          git config user.name "ALN-AutoFixer"
          git config user.email "autofix@aln.dev"
          git add .
          git commit -m "ALN: Automatic repository-wide file correction" || echo "No changes to commit"
          git push
