name: ALN File Correction & Live Repo Sync

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  correct-and-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.ALN_PUSH_TOKEN }}  # PAT with workflow scope

      - name: Normalize Line Endings
        run: |
          find . -type f ! -path "./.git/*" -exec dos2unix {} \;

      - name: Remove Trailing Whitespace
        run: |
          find . -type f ! -path "./.git/*" -exec sed -i "s/[ \t]*$//" {} \;

      - name: Format ALN files (if '.aln' extension)
        run: |
          for file in $(find . -type f -name "*.aln"); do
            sed -i "s/\r//g" "$file"
          done

      - name: Auto-commit & Safe Push with Retry
        shell: bash
        run: |
          set -e

          git config user.name "ALN-AutoFixer"
          git config user.email "autofix@aln.dev"

          git add .

          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -m "ALN: Automatic repository-wide file correction"

          git remote set-url origin https://x-access-token:${{ secrets.ALN_PUSH_TOKEN }}@github.com/Doctor0Evil/ALN_Programming_Language.git

          attempt_push() {
            git pull --rebase origin main || return 1
            git push origin main || return 1
          }

          for i in 1 2 3; do
            if attempt_push; then
              echo "Push successful."
              exit 0
            fi
            echo "Push failed (attempt $i). Retrying in $((i*5))s..."
            sleep $((i*5))
          done

          echo "Push failed after 3 attempts."
          exit 1
