name: Meta Orchestrator with Livingroom Runner

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/**"

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: orchestrator-${{ github.ref }}
  cancel-in-progress: false

jobs:
  preflight-fix:
    name: Preflight Fix (Ubuntu)
    uses: ./.github/workflows/workflow_fixer.yml
    with:
      caller: orchestrator
      depth: 2

  generator:
    name: Workflow Generator (Ubuntu)
    needs: preflight-fix
    uses: ./.github/workflows/workflow_generator.yml
    with:
      create_samples: true
      bot_name: "actions-user"
      bot_email: "actions-user@users.noreply.github.com"

  validator:
    name: Workflow Validator (Ubuntu)
    needs: [preflight-fix, generator]
    uses: ./.github/workflows/workflow_validator.yml

  windows-tests:
    name: Livingroom Runner Tasks (Self‑hosted Windows)
    needs: validator
    runs-on: [self-hosted, Windows, X64]
    if: success() # only run if validator passed
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Confirm Runner Context
        shell: pwsh
        run: |
          Write-Host "Runner Name: $env:RUNNER_NAME"
          Write-Host "Runner OS: $env:RUNNER_OS $env:RUNNER_ARCH"
          Write-Host "Running on Livingroom self-hosted Windows runner."

      - name: Build or Test on Windows
        shell: pwsh
        run: |
          Write-Host "Running Windows-specific build/test tasks..."
          # Example: invoke a PowerShell test script
          if (Test-Path .\scripts\windows_build.ps1) {
            pwsh .\scripts\windows_build.ps1
          } else {
            Write-Host "No Windows build script found — skipping."
          }

  recovery:
    name: Recovery Path (Ubuntu)
    needs: [validator, windows-tests]
    if: failure()
    uses: ./.github/workflows/workflow_fixer.yml
    with:
      caller: orchestrator-recovery
      depth: 1
